---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: restrict-resource-usage-n-a
  namespace: default
spec:
  hard:
    cpu: "2"
    memory: "4Gi"
    requests.cpu: "500m"
    requests.memory: "512Mi"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-external-traffic-n-a
  namespace: default
spec:
  podSelector:
    matchLabels:
      vulnerability: n-a
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - to:
    - podSelector: {}
